### ISSUE TITLE
Bump used SDL version

### ISSUE THREAD

**Issue by pktiuk** [flathub/io.github.antimicrox.antimicrox#15]
Current flatpak version of AntiMicroX uses SDL `2.0.16`   
This one is a bit outdated (and causes some issues like: https://github.com/libsdl-org/SDL/issues/5933)
It would be good to bump the used version inside of this package.

@gombosg  
Is it easily doable?

**Comment by gombosg** [comment]
#17 fixed this then hopefully?

**Comment by pktiuk** [comment]
Yes
